use super::snapshot::MindSnapshot;

pub fn render(snap: &MindSnapshot) -> String {
    let mut out = String::new();
    out.push_str(&format!("# Mind — {} — {}\n\n", snap.board_name, snap.generated_at.format("%Y-%m-%dT%H:%MZ")));

    // Board Health
    out.push_str("## Board Health\n");
    out.push_str(&format!("- Total {} cards\n", snap.stats.total));
    let cols = ["todo", "doing", "review", "done"];
    for col in cols {
        let n = snap.stats.by_column.get(col).copied().unwrap_or(0);
        out.push_str(&format!("  - {}: {}\n", col, n));
    }
    if !snap.stats.by_priority.is_empty() {
        out.push_str("- By priority: ");
        let parts: Vec<String> = snap.stats.by_priority.iter().map(|(k, v)| format!("{}:{}", k, v)).collect();
        out.push_str(&parts.join(", "));
        out.push('\n');
    }
    out.push('\n');

    // Sprint
    if let Some(ref s) = snap.active_sprint {
        out.push_str("## Sprint\n");
        out.push_str(&format!("- Active: {} (start: {}, end: {})\n\n", s.name, s.start.as_deref().unwrap_or("-"), s.end.as_deref().unwrap_or("-")));
    }

    // Blockers
    out.push_str("## Blockers\n");
    if snap.blockers.is_empty() {
        out.push_str("- None\n\n");
    } else {
        for b in &snap.blockers {
            out.push_str(&format!("- {} ({}) blocked by {}\n", b.title, b.card_id, b.blocked_by.join(", ")));
        }
        out.push('\n');
    }

    // Stale
    out.push_str("## Stale (>7d)\n");
    if snap.stale_cards.is_empty() {
        out.push_str("- None\n\n");
    } else {
        for s in &snap.stale_cards {
            out.push_str(&format!("- {} ({}, {}, {}d)\n", s.title, s.id, s.column, s.days));
        }
        out.push('\n');
    }

    // Velocity
    if let Some(ref v) = snap.velocity {
        out.push_str("## Velocity\n");
        out.push_str(&format!("- Done {} cards, {} points, avg {:.1}\n\n", v.total_done, v.total_points, v.avg_effort));
    }

    // Next Actions
    out.push_str("## Next Actions\n");
    for (i, a) in snap.next_actions.iter().enumerate() {
        out.push_str(&format!("{}. `{}` — {}\n", i + 1, a.action, a.reason));
    }
    out.push('\n');

    // Recent history
    out.push_str("## Recent History (10)\n");
    if snap.recent_history.is_empty() {
        out.push_str("- No history\n\n");
    } else {
        for h in &snap.recent_history {
            out.push_str(&format!("- {} {} {} {}→{}\n", h.at, h.op, h.card, h.old_value.as_deref().unwrap_or("-"), h.new_value.as_deref().unwrap_or("-")));
        }
        out.push('\n');
    }

    // Recent sessions
    out.push_str("## Recent Sessions (10)\n");
    if snap.recent_sessions.is_empty() {
        out.push_str("- No sessions\n\n");
    } else {
        for s in &snap.recent_sessions {
            out.push_str(&format!("- {} {} {}\n", s.at, s.id, s.summary.as_deref().unwrap_or("")));
        }
        out.push('\n');
    }

    // Top memories
    out.push_str("## Top Memories\n");
    if snap.top_memories.is_empty() {
        out.push_str("- No memories. Add with `barkcli memory add \"...\" --tier long`\n");
    } else {
        for m in &snap.top_memories {
            out.push_str(&format!("- [{}] {}\n", m.tier.display_name(), m.content.chars().take(120).collect::<String>()));
        }
    }
    out.push('\n');

    out.push_str("---\n*Generated by `barkcli mind sync` — paste this into agent prompt for project context.*\n");
    out
}
