use anyhow::{Context, Result};
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::path::PathBuf;

use crate::models::Sprint;
use crate::storage::board_dir::find_board_dir;
use crate::storage::board_file::read_board;
use crate::storage::history::HistoryEntry;
use crate::models::session::SessionEntry;
use crate::memory::store::MemoryEntry;

/// Board stats by column/priority/label
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BoardStats {
    pub total: usize,
    pub by_column: HashMap<String, usize>,
    pub by_priority: HashMap<String, usize>,
    pub by_label: HashMap<String, usize>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Blocker {
    pub card_id: String,
    pub title: String,
    pub blocked_by: Vec<String>,
    pub column: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StaleCard {
    pub id: String,
    pub title: String,
    pub column: String,
    pub days: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NextAction {
    pub action: String,
    pub reason: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VelocityReport {
    pub total_done: usize,
    pub total_points: u32,
    pub avg_effort: f32,
}

/// Derived snapshot — not edited by hand, regenerated by `barkcli mind sync`
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MindSnapshot {
    pub board_name: String,
    pub generated_at: DateTime<Utc>,
    pub stats: BoardStats,
    pub active_sprint: Option<Sprint>,
    pub blockers: Vec<Blocker>,
    pub stale_cards: Vec<StaleCard>,
    pub next_actions: Vec<NextAction>,
    pub recent_history: Vec<HistoryEntry>,
    pub recent_sessions: Vec<SessionEntry>,
    pub top_memories: Vec<MemoryEntry>,
    pub velocity: Option<VelocityReport>,
}

pub fn mind_path(board_name: &str) -> Result<PathBuf> {
    let board_dir = find_board_dir()?;
    let dir = board_dir.join("mind");
    std::fs::create_dir_all(&dir).ok();
    Ok(dir.join(format!("{}.json", board_name)))
}

pub fn digest_path(board_name: &str) -> Result<PathBuf> {
    let board_dir = find_board_dir()?;
    let dir = board_dir.join("mind");
    std::fs::create_dir_all(&dir).ok();
    Ok(dir.join(format!("{}.md", board_name)))
}

/// Build snapshot from current board state (offline, no LLM)
pub fn build(board_name: &str) -> Result<MindSnapshot> {
    let board = read_board(board_name).context(format!("board '{}' not found", board_name))?;

    // Stats
    let mut by_column: HashMap<String, usize> = HashMap::new();
    let mut by_priority: HashMap<String, usize> = HashMap::new();
    let mut by_label: HashMap<String, usize> = HashMap::new();
    for c in &board.cards {
        *by_column.entry(c.column.clone()).or_insert(0) += 1;
        *by_priority.entry(c.priority.clone()).or_insert(0) += 1;
        for l in &c.labels {
            *by_label.entry(l.clone()).or_insert(0) += 1;
        }
    }
    let stats = BoardStats {
        total: board.cards.len(),
        by_column: by_column.clone(),
        by_priority,
        by_label,
    };

    // Blockers
    let mut blockers = Vec::new();
    for c in &board.cards {
        let mut blocked_by = Vec::new();
        if let Some(ref b) = c.blocked_by {
            if !b.is_empty() {
                blocked_by.push(b.clone());
            }
        }
        for link in &c.links {
            if link.ty == crate::models::card::LinkType::BlockedBy {
                blocked_by.push(link.target.clone());
            }
        }
        if !blocked_by.is_empty() {
            blockers.push(Blocker {
                card_id: c.id.clone(),
                title: c.title.clone(),
                blocked_by,
                column: c.column.clone(),
            });
        }
    }

    // Stale (>7 days in todo/doing/review, not done)
    let now = Utc::now();
    let stale_cards: Vec<StaleCard> = board
        .cards
        .iter()
        .filter(|c| c.column != "done")
        .filter_map(|c| {
            let days = (now - c.updated_at).num_days();
            if days > 7 {
                Some(StaleCard {
                    id: c.id.clone(),
                    title: c.title.clone(),
                    column: c.column.clone(),
                    days,
                })
            } else {
                None
            }
        })
        .collect();

    // Next actions heuristics
    let mut next_actions: Vec<NextAction> = Vec::new();
    let todo_no_ac: Vec<&crate::models::card::Card> = board
        .cards
        .iter()
        .filter(|c| c.column == "todo" && c.checklist.is_empty())
        .collect();
    if !todo_no_ac.is_empty() {
        let sample = &todo_no_ac[0];
        next_actions.push(NextAction {
            action: format!("barkcli plan {} --tasks", sample.id),
            reason: format!("{} todo cards without AC", todo_no_ac.len()),
        });
    }
    // Pending tasks?
    let board_dir = find_board_dir()?;
    let tasks_path = board_dir.join("tasks").join(format!("{}.json", board_name));
    let pending_tasks = if tasks_path.exists() {
        crate::agent::queue::TaskQueue::load(&tasks_path)
            .map(|q| q.by_status(&crate::agent::queue::TaskStatus::Pending).len())
            .unwrap_or(0)
    } else {
        0
    };
    if pending_tasks > 0 {
        next_actions.push(NextAction {
            action: "barkcli dispatch".into(),
            reason: format!("{} pending tasks", pending_tasks),
        });
    }
    let review_count = by_column.get("review").copied().unwrap_or(0);
    if review_count > 0 {
        next_actions.push(NextAction {
            action: "barkcli review --all --auto".into(),
            reason: format!("{} cards in review", review_count),
        });
    }
    if next_actions.is_empty() {
        if board.cards.is_empty() {
            next_actions.push(NextAction {
                action: "barkcli add \"Your first task\"".into(),
                reason: "board empty".into(),
            });
        } else {
            next_actions.push(NextAction {
                action: "barkcli add \"...\" or barkcli intake \"...\"".into(),
                reason: "no immediate blockers/stale — keep shipping".into(),
            });
        }
    }

    // Recent history (last 10)
    let recent_history = crate::storage::history::read_history(board_name)
        .unwrap_or_default()
        .into_iter()
        .rev()
        .take(10)
        .collect();

    // Recent sessions (last 10)
    let recent_sessions = crate::storage::sessions::read_sessions(board_name)
        .unwrap_or_default()
        .into_iter()
        .rev()
        .take(10)
        .collect();

    // Top memories (search "project conventions" or just recent 3)
    let top_memories = {
        let store = crate::memory::store::MemoryStore::open(board_name).ok();
        if let Some(s) = store {
            // Prefer search for conventions, fall back to recent
            let res = s.search("project conventions patterns decisions", 3);
            if res.is_empty() {
                let recent: Vec<MemoryEntry> = s.recent(3).into_iter().cloned().collect();
                recent
            } else {
                res.into_iter().cloned().collect()
            }
        } else {
            Vec::new()
        }
    };

    // Active sprint — first sprint with no end or start <= today
    let active_sprint = {
        let sprints = crate::storage::sprints::read_sprints(board_name).unwrap_or_default();
        // Simplest: pick first with end.is_none()
        sprints.into_iter().find(|s| s.end.is_none())
    };

    // Velocity
    let velocity = {
        let done_cards: Vec<&crate::models::card::Card> = board.cards.iter().filter(|c| c.column == "done").collect();
        let total_done = done_cards.len();
        let total_points: u32 = done_cards.iter().filter_map(|c| c.effort).sum();
        let avg_effort = if total_done > 0 {
            total_points as f32 / total_done as f32
        } else {
            0.0
        };
        if total_done > 0 {
            Some(VelocityReport {
                total_done,
                total_points,
                avg_effort,
            })
        } else {
            None
        }
    };

    Ok(MindSnapshot {
        board_name: board_name.to_string(),
        generated_at: Utc::now(),
        stats,
        active_sprint,
        blockers,
        stale_cards,
        next_actions,
        recent_history,
        recent_sessions,
        top_memories,
        velocity,
    })
}

pub fn save(snapshot: &MindSnapshot) -> Result<()> {
    let path = mind_path(&snapshot.board_name)?;
    crate::util::lock::with_lock(&path, || {
        let json = serde_json::to_string_pretty(snapshot).context("serialize mind")?;
        let tmp = path.with_extension(format!(
            "{}.tmp",
            path.extension().and_then(|e| e.to_str()).unwrap_or("json")
        ));
        std::fs::write(&tmp, json).context("write tmp mind")?;
        std::fs::rename(&tmp, &path).context("rename mind")?;
        Ok(())
    })?;
    // also write digest.md
    let dpath = digest_path(&snapshot.board_name)?;
    let digest = crate::mind::digest::render(snapshot);
    std::fs::write(&dpath, digest).context("write digest")?;
    Ok(())
}

pub fn load(board_name: &str) -> Result<MindSnapshot> {
    let path = mind_path(board_name)?;
    let content = std::fs::read_to_string(&path).context("read mind snapshot — run barkcli mind sync")?;
    let snap: MindSnapshot = serde_json::from_str(&content).context("parse mind snapshot")?;
    Ok(snap)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::models::{Board, Card};
    use crate::storage::board_file;

    #[test]
    fn snapshot_build_from_fixture() {
        // Build in temp dir
        let tmp = std::env::temp_dir().join(format!("bark-mind-{}", uuid::Uuid::new_v4()));
        std::fs::create_dir_all(tmp.join(".board")).unwrap();
        let orig = std::env::current_dir().unwrap();
        std::env::set_current_dir(&tmp).unwrap();

        let mut board = Board::new("Test");
        let mut c1 = Card::new("c1", "Todo card", "todo");
        c1.updated_at = Utc::now() - chrono::Duration::days(10);
        let c2 = Card::new("c2", "Done card", "done");
        let mut c3 = Card::new("c3", "Blocked", "todo");
        c3.blocked_by = Some("c1".into());
        board.cards.push(c1);
        board.cards.push(c2);
        board.cards.push(c3);
        board_file::write_board("test", &board).unwrap();

        let snap = build("test").unwrap();
        assert_eq!(snap.stats.total, 3);
        assert_eq!(snap.blockers.len(), 1);
        assert_eq!(snap.stale_cards.len(), 1); // c1 stale
        assert!(!snap.next_actions.is_empty());

        std::env::set_current_dir(orig).unwrap();
        std::fs::remove_dir_all(&tmp).ok();
    }
}
