use sha2::{Sha256, Digest};
use std::fs;
use std::path::PathBuf;

/// SHA256 hashes of valid license keys. Generated by `scripts/gen-license`.
/// Add new hashes when you sell more licenses.
const VALID_LICENSES: &[&str] = &[
    "236981f7cedf48f73ae0360f9f546ee9840af3583447df463e30bd4823795a45",
];

fn license_path() -> PathBuf {
    let home = dirs().unwrap_or_else(|| PathBuf::from("."));
    home.join(".board").join("license")
}

fn dirs() -> Option<PathBuf> {
    std::env::var("HOME")
        .or_else(|_| std::env::var("USERPROFILE"))
        .ok()
        .map(PathBuf::from)
}

fn hash_key(key: &str) -> String {
    let mut hasher = Sha256::new();
    hasher.update(key.trim().as_bytes());
    hex::encode(hasher.finalize())
}

pub fn is_licensed() -> bool {
    let path = license_path();
    if !path.exists() {
        return false;
    }
    match fs::read_to_string(&path) {
        Ok(key) => {
            let h = hash_key(&key);
            VALID_LICENSES.contains(&h.as_str())
        }
        Err(_) => false,
    }
}

pub fn activate(key: &str) -> Result<(), String> {
    let h = hash_key(key);

    if !VALID_LICENSES.contains(&h.as_str()) {
        return Err(format!(
            "Invalid license key '{}'.\nGet a valid key at https://getbarkcli.dev",
            key
        ));
    }

    let path = license_path();
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|e| format!("Cannot create ~/.board: {}", e))?;
    }

    fs::write(&path, key.trim()).map_err(|e| format!("Cannot write license: {}", e))?;

    println!("✓ barkcli Pro activated!");
    println!("  License: {}", key);
    Ok(())
}

pub fn status() {
    if is_licensed() {
        println!("barkcli Pro — activated ✓");
    } else {
        println!("barkcli (free tier)");
        println!("Upgrade to Pro at https://getbarkcli.dev");
    }
}

pub fn check_pro(cmd: &str) -> bool {
    if is_licensed() {
        return true;
    }
    eprintln!(
        "{} requires barkcli Pro. Get a license at https://getbarkcli.dev",
        cmd
    );
    false
}
