export interface Comparison {
  slug: string;
  name: string;
  tagline: string;
  description: string;
  barkcliAdvantages: string[];
  competitorAdvantages: string[];
  features: { feature: string; barkcli: string; competitor: string; barkcliWins?: boolean }[];
  verdict: string;
  bestForBarkcli: string;
  bestForCompetitor: string;
}

export const comparisons: Comparison[] = [
  {
    slug: "linear",
    name: "Linear",
    tagline: "barkcli vs Linear — Git-native vs Cloud-first",
    description: "Linear is a polished SaaS issue tracker. barkcli keeps tasks in your repo as YAML files — no cloud, no accounts, no subscriptions.",
    barkcliAdvantages: [
      "Tasks live in your repo — diff, merge, grep them like code",
      "Zero cost — MIT licensed, no per-seat pricing",
      "Works offline — no internet required",
      "AI agents can read tasks directly from the codebase",
      "Branch-aware — tasks travel with feature branches",
    ],
    competitorAdvantages: [
      "Polished UI with keyboard-first design",
      "Built-in cycles and triage workflow",
      "Strong team collaboration features",
      "Native GitHub/GitLab integration",
    ],
    features: [
      { feature: "Data Location", barkcli: "Your repo (YAML)", competitor: "Cloud (proprietary)" },
      { feature: "Offline Support", barkcli: "Full", competitor: "Limited" },
      { feature: "Cost", barkcli: "Free (MIT)", competitor: "$8-16/seat/month" },
      { feature: "Git Integration", barkcli: "Native (tasks = files)", competitor: "Via PRs/branches" },
      { feature: "AI Agent Access", barkcli: "Direct file access", competitor: "API only" },
      { feature: "Custom Workflows", barkcli: "YAML columns", competitor: "Workflow builder" },
      { feature: "Team Collaboration", barkcli: "Git push/pull", competitor: "Real-time sync" },
      { feature: "Self-Host", barkcli: "Yes (it's a binary)", competitor: "No" },
    ],
    verdict: "Choose barkcli if you want tasks that live with your code and work offline. Choose Linear if you need polished team collaboration and don't mind the cloud.",
    bestForBarkcli: "Solo developers, small teams, AI-heavy workflows",
    bestForCompetitor: "Teams needing real-time collaboration and polished UI",
  },
  {
    slug: "jira",
    name: "Jira",
    tagline: "barkcli vs Jira — Simple vs Enterprise",
    description: "Jira is the enterprise standard with 25 years of history. barkcli is a single binary with zero configuration.",
    barkcliAdvantages: [
      "Setup in 10 seconds vs hours of Jira configuration",
      "No server administration required",
      "Tasks are human-readable YAML, not Jira markup",
      "Free forever — no enterprise licensing",
      "AI agents can read tasks without API calls",
    ],
    competitorAdvantages: [
      "3000+ marketplace apps",
      "Enterprise compliance (SOC 2, ISO 27001)",
      "Jira Service Management for IT",
      "Advanced reporting and dashboards",
    ],
    features: [
      { feature: "Setup Time", barkcli: "10 seconds", competitor: "Hours/days" },
      { feature: "Data Location", barkcli: "Your repo", competitor: "Cloud/Data Center" },
      { feature: "Cost", barkcli: "Free", competitor: "$8-17/seat/month" },
      { feature: "Configuration", barkcli: "YAML file", competitor: "Web UI (complex)" },
      { feature: "Performance", barkcli: "Instant (local)", competitor: "1-3s page loads" },
      { feature: "Offline", barkcli: "Full", competitor: "No" },
      { feature: "Marketplace", barkcli: "None", competitor: "3000+ apps" },
      { feature: "Enterprise Features", barkcli: "Basic", competitor: "Full suite" },
    ],
    verdict: "Choose barkcli if you want simplicity and speed. Choose Jira if you need enterprise compliance and extensive integrations.",
    bestForBarkcli: "Developers who hate Jira, small teams, side projects",
    bestForCompetitor: "Enterprise teams, compliance-heavy industries",
  },
  {
    slug: "height",
    name: "Height",
    tagline: "barkcli vs Height — Local-first vs AI-first",
    description: "Height is an AI-native project manager. barkcli is a git-native task layer with AI integration via MCP.",
    barkcliAdvantages: [
      "Tasks live in your repo — version controlled with your code",
      "No subscription required",
      "MCP server for coding agent integration",
      "Works with any AI tool (Claude, GPT, local models)",
      "No vendor lock-in — plain YAML files",
    ],
    competitorAdvantages: [
      "AI auto-triage and auto-labeling",
      "Real-time multiplayer collaboration",
      "Built-in Gantt charts",
      "Multiple synced views (list, board, calendar)",
    ],
    features: [
      { feature: "AI Integration", barkcli: "MCP server (BYO model)", competitor: "Built-in AI copilot" },
      { feature: "Data Location", barkcli: "Your repo", competitor: "Cloud" },
      { feature: "Cost", barkcli: "Free", competitor: "$8-12/seat/month" },
      { feature: "Collaboration", barkcli: "Git-based", competitor: "Real-time multiplayer" },
      { feature: "Offline", barkcli: "Full", competitor: "Limited" },
      { feature: "Views", barkcli: "CLI, TUI, Web, VS Code", competitor: "List, Board, Gantt, Calendar" },
      { feature: "Automation", barkcli: "Git hooks + scripts", competitor: "AI auto-triage" },
    ],
    verdict: "Choose barkcli if you want tasks in your repo with AI flexibility. Choose Height if you want AI-managed project management with real-time collaboration.",
    bestForBarkcli: "Developers wanting git-native tasks, AI tinkerers",
    bestForCompetitor: "Teams wanting AI-managed workflows out of the box",
  },
  {
    slug: "plane",
    name: "Plane",
    tagline: "barkcli vs Plane — Binary vs Self-hosted",
    description: "Plane is an open-source Linear alternative you self-host. barkcli is a single binary with no server required.",
    barkcliAdvantages: [
      "No server to maintain — it's just a binary",
      "Tasks are YAML files, not database rows",
      "Instant setup vs Docker compose + database",
      "AI agents read tasks directly from files",
      "Git-native version control for tasks",
    ],
    competitorAdvantages: [
      "Full-featured web UI",
      "Self-host with full data control",
      "Pages (Notion-like docs)",
      "BYO LLM for AI features",
    ],
    features: [
      { feature: "Setup", barkcli: "Single binary", competitor: "Docker + database" },
      { feature: "Data Location", barkcli: "Your repo (YAML)", competitor: "Self-hosted DB" },
      { feature: "Cost", barkcli: "Free", competitor: "Free (self-host) / $6-13/seat" },
      { feature: "Web UI", barkcli: "Optional (barkcli serve)", competitor: "Full-featured" },
      { feature: "Offline", barkcli: "Full", competitor: "Self-host only" },
      { feature: "Maintenance", barkcli: "None", competitor: "Server updates" },
      { feature: "AI Features", barkcli: "MCP + local LLM", competitor: "BYO LLM module" },
    ],
    verdict: "Choose barkcli if you want zero maintenance and git-native tasks. Choose Plane if you want a full web UI with self-hosting control.",
    bestForBarkcli: "Developers who want simplicity, no server overhead",
    bestForCompetitor: "Teams wanting a Linear-like UI they can self-host",
  },
  {
    slug: "trello",
    name: "Trello",
    tagline: "barkcli vs Trello — Code vs Cloud",
    description: "Trello is the original kanban board. barkcli brings kanban to your terminal and repo.",
    barkcliAdvantages: [
      "No cloud dependency — works offline",
      "Tasks are version controlled with your code",
      "CLI, TUI, and web interfaces",
      "Free forever — no power-up fees",
      "AI agents can access tasks directly",
    ],
    competitorAdvantages: [
      "Visual drag-and-drop interface",
      "Power-ups for integrations",
      "Mobile apps",
      "Team boards and permissions",
    ],
    features: [
      { feature: "Data Location", barkcli: "Your repo", competitor: "Cloud" },
      { feature: "Cost", barkcli: "Free", competitor: "Free / $5-10/user/month" },
      { feature: "Offline", barkcli: "Full", competitor: "Limited" },
      { feature: "Automation", barkcli: "Git hooks", competitor: "Butler rules" },
      { feature: "Integrations", barkcli: "Git ecosystem", competitor: "Power-ups" },
      { feature: "Mobile", barkcli: "No", competitor: "Yes" },
      { feature: "API", barkcli: "MCP server", competitor: "REST API" },
    ],
    verdict: "Choose barkcli if you live in the terminal and want tasks with your code. Choose Trello if you want visual simplicity with mobile access.",
    bestForBarkcli: "Terminal users, developers, open source contributors",
    bestForCompetitor: "Non-technical teams, visual learners",
  },
  {
    slug: "notion",
    name: "Notion",
    tagline: "barkcli vs Notion — Tasks vs Everything",
    description: "Notion is an all-in-one workspace. barkcli is a focused task layer for developers.",
    barkcliAdvantages: [
      "Purpose-built for task management, not a docs tool",
      "Git-native — tasks version controlled with code",
      "No subscription required",
      "AI agents read tasks without API calls",
      "Works offline — no internet needed",
    ],
    competitorAdvantages: [
      "All-in-one docs, databases, wikis",
      "Beautiful templates and UI",
      "Real-time collaboration",
      "Notion AI for writing and analysis",
    ],
    features: [
      { feature: "Focus", barkcli: "Task management only", competitor: "Everything (docs, DBs, wiki)" },
      { feature: "Data Location", barkcli: "Your repo", competitor: "Cloud" },
      { feature: "Cost", barkcli: "Free", competitor: "Free / $8-15/user/month" },
      { feature: "Performance", barkcli: "Instant (local)", competitor: "Slower (cloud)" },
      { feature: "Offline", barkcli: "Full", competitor: "Limited" },
      { feature: "AI", barkcli: "MCP server", competitor: "Notion AI" },
      { feature: "Version Control", barkcli: "Git native", competitor: "Page history" },
    ],
    verdict: "Choose barkcli if you want focused, fast task management in your repo. Choose Notion if you need an all-in-one workspace for docs, wikis, and tasks.",
    bestForBarkcli: "Developers who want speed and git integration",
    bestForCompetitor: "Teams needing docs + tasks + wiki in one place",
  },
  {
    slug: "github-projects",
    name: "GitHub Projects",
    tagline: "barkcli vs GitHub Projects — Local vs Platform",
    description: "GitHub Projects lives on GitHub. barkcli lives in your repo — works with any git host.",
    barkcliAdvantages: [
      "Works with GitLab, Bitbucket, or any git host",
      "Tasks are local files — no internet required",
      "CLI and TUI interfaces, not just web",
      "AI agents read tasks without API rate limits",
      "No GitHub dependency",
    ],
    competitorAdvantages: [
      "Native GitHub integration",
      "Free for public repos",
      "Issues and PRs link automatically",
      "GitHub Actions integration",
    ],
    features: [
      { feature: "Git Host", barkcli: "Any (git-native)", competitor: "GitHub only" },
      { feature: "Data Location", barkcli: "Your repo", competitor: "GitHub cloud" },
      { feature: "Cost", barkcli: "Free", competitor: "Free" },
      { feature: "Offline", barkcli: "Full", competitor: "No" },
      { feature: "CLI", barkcli: "Full-featured", competitor: "gh CLI (limited)" },
      { feature: "Custom Fields", barkcli: "YAML properties", competitor: "Custom fields" },
      { feature: "Automation", barkcli: "Git hooks", competitor: "GitHub Actions" },
    ],
    verdict: "Choose barkcli if you want portable, offline-capable tasks. Choose GitHub Projects if you're all-in on GitHub and want tight issue/PR integration.",
    bestForBarkcli: "Multi-platform teams, offline workflows, AI agents",
    bestForCompetitor: "GitHub-centric teams wanting free project management",
  },
  {
    slug: "height-alternatives",
    name: "All PM Tools",
    tagline: "barkcli vs Traditional PM — The Developer's Choice",
    description: "Traditional PM tools are cloud SaaS. barkcli is a local binary that keeps tasks in your repo.",
    barkcliAdvantages: [
      "Tasks are code — diff, merge, grep, version control",
      "Zero cost — no subscriptions, no per-seat pricing",
      "Works offline — no internet, no accounts",
      "AI agents read tasks directly from files",
      "Portable — works with any git host",
    ],
    competitorAdvantages: [
      "Rich web UIs with drag-and-drop",
      "Real-time team collaboration",
      "Mobile apps",
      "Enterprise compliance and permissions",
    ],
    features: [
      { feature: "Data Ownership", barkcli: "Full (your repo)", competitor: "Vendor lock-in" },
      { feature: "Cost", barkcli: "Free forever", competitor: "$5-20/seat/month" },
      { feature: "Setup", barkcli: "10 seconds", competitor: "Minutes to hours" },
      { feature: "Offline", barkcli: "Full", competitor: "Limited or none" },
      { feature: "AI Integration", barkcli: "MCP (open standard)", competitor: "Proprietary APIs" },
      { feature: "Version Control", barkcli: "Git native", competitor: "Platform-specific" },
      { feature: "Performance", barkcli: "Instant (local)", competitor: "Network-dependent" },
    ],
    verdict: "barkcli is for developers who want tasks as code. Traditional PM tools are for teams who want polished UIs and don't mind the cloud.",
    bestForBarkcli: "Developers, terminal users, privacy-conscious teams",
    bestForCompetitor: "Non-technical teams, enterprise, visual learners",
  },
];

export function getComparisonBySlug(slug: string): Comparison | undefined {
  return comparisons.find((c) => c.slug === slug);
}
